# Generated by Django 6.1.1 on 2026-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
