# Generated by Django 6.1.1 on 2026-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True),
        ),
    ]
